### ISSUE TITLE
on CouchPotato ThePirateBay search does not work

### ISSUE THREAD

**Issue by cicobalico** [Influencer/UNplugged#2]
As described here https://github.com/RuudBurger/CouchPotatoServer/issues/671
Couchpotato does not recognize the magnet links and this is the log everytime you try downloading them

   [hpotato.core.plugins.base] Failed opening url in ThePirateBay: magnet:?      xt=urn:btih:b0225eb5a61557666cd73feb2ea99d695ab949b4&dn=The+Bourne+Identity.2002.DVDRIP_ENG.avi&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A6969&tr=udp%3A%2F%2Ftracker.ccc.de%3A80 Traceback (most recent call last):
    File "/mnt/disk1/couchpotato_v2/couchpotato/core/plugins/base.py", line 139, in urlopen
    data = urllib2.urlopen(request, timeout = timeout).read()
    URLError: <urlopen error unknown url type: magnet>

**Comment by spylex** [comment]
Im afraid this is nothing to do with the plugins but rather CouchPotato itself. Please have a look at their forum!
