### ISSUE TITLE
LazyLibrarian

### ISSUE THREAD

**Issue by Markyb0y** [Influencer/UNplugged#6]
Any Chance of getting LazyLibrarian added as a plugin?

original code based on Headphones but its for eBooks
https://github.com/itsmegb/LazyLibrarian

Looking forward to using many of these plugins on my first UNraid build starting next month when I get my hands on my new hardware  :o

cheers

Mark

**Comment by Benni-chan** [comment]
as far as i can see, there are no dependencies for this tool, except python...
there would be a need for update via plugin ui. and we would have to check, what command parameters are supported and what we have to write into the config ourself...

but i guess, we could mainly take one existigng plugin and change some code. should not be too much work. If I got some time, I'll take a look.

**Comment by Benni-chan** [comment]
i've just noticed, that there is already a plugin available for this.
you can find it here: https://github.com/W-W/unRAID
don't know, if it still works...

**Comment by Markyb0y** [comment]
The plugin you linked to does not work as far as I can see, all your unplugged apps install fine and show in the settings screen etc

Also, I asked on the other link if they could change the source to use the correct fork, but I have not even had any response
Can you please make the LazyLibrarian plugin use https://github.com/LibrarianMike/LazyLibrarian.git

this fork is being worked on regularly and is currently the only version I can get working normally, so would love to have this version on unraid

Many thanks
